version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5.3
      - image: postgres:9.5
        environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=amazing_password
        - POSTGRES_DB=postgres

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install deps
          command: |
            sudo pip3 install virtualenv
            virtualenv venv
            source venv/bin/activate
            pip3 install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # Run the tests
      - run:
          name: Run tests
          command: |
            source venv/bin/activate
            pep8 --max-line-length=100 `find . -name "*.py" -not -path "./venv*"`
            nose2
